### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by omayma96** [omayma96/Js-workshops#1]
- [x] histoire

- [x] variables

- [x] tableaux

- [x] boocle

- [x] meilleure pratique

- [x] scope

- [x] closure

- [x] this

- [x]  fonction

- [x]  prototype

- [x] objets

- [x] dom 

- [x] bom 

- [x] events

**Comment by omayma96** [comment]
j'ai une idée sur l'histoire de Js et sur ses débuts ainsi quelques informations sur ECMAScript

**Comment by omayma96** [comment]
Je suis arrivée au stade de faire la différence entre les variables ( Var , Let , Const ) et je sais quand on et pourquoi on utilise chaque type. 
Ainsi j'ai une idée sur les Booléens. 
Et je sais maintenant faire la différence entre une variable globale et une variable local.

**Comment by omayma96** [comment]
Je sais maintenant comment déclaré un tableau en Js et ainsi comment avoir le Control sur ses tableaux

**Comment by youssefbm** [comment]
keep going the good work :).

**Comment by omayma96** [comment]
j'ai vu les boocles et j'ai une idée bien précise sur leurs rôles importants dans un programme

**Comment by omayma96** [comment]
j'ai vu la notion des fonctions dans Js ainsi que leurs importance

**Comment by omayma96** [comment]
on a vu ce matin dans une veille la notion de scope et j'ai très bien compris ce terme

**Comment by youssefbm** [comment]
Très bien, J'espère que toute la classe a compris le contenu des deux présentation

**Comment by youssefbm** [comment]
N'oubliez pas d'ajouter les objets dans votre checklist.

**Comment by omayma96** [comment]
j'ai compris la notion d'objet , comment on déclare ce dernier et comment on utilise

**Comment by omayma96** [comment]
j'ai compris la notion de "closure "

**Comment by omayma96** [comment]
**j'ai terminé la partie documentation sur "THIS " et " PROTOTYPE" , j'ai presque compris la notion de ces derniers mais j'ai quelques ambiguïtés comme si j'ai l'impression que j'ai pas très bien compris ou il y quelques choses qui cloches**
