### ISSUE TITLE
veille DOM & BOM

### ISSUE THREAD

**Issue by omayma96** [omayma96/Js-workshops#4]
- [x] comprendre DOM

- [x] comprendre BOM

- [x] trouvez des exercices 

- [x] réalisez le SlideShow

- [x] voir la meilleure façon pour expliquer le contenu de la veille

**Comment by youssefbm** [comment]
Dans votre veille tu peux te baser sur ce tutoriel : https://stph.scenari-community.org/doc/dom/co/domAC01dom.html
négligez la partie XML

**Comment by omayma96** [comment]
merci pour avoir partager ce tutoriel , je vais le prendre en considération pour que je puisse réaliser ma veille
